table _Measures
	lineageTag: d8829f41-b694-42f2-bd00-f837f1afcc59

	measure Total_AUM_Cr = SUM(aum_amfi_monthly_clean[aum_cr]) / 10000000
		lineageTag: 71a7716a-a5f4-4e15-a6de-7a2e5109bccf

		formatStringDefinition = "##,##,##,##0.00"" Cr"";-##,##,##,##0.00"" Cr"";0.00"" Cr"""

	measure Avg_Sharpe_Ratio = AVERAGEX(FILTER(fund_metrics, fund_metrics[sharpe_ratio] <> BLANK()), fund_metrics[sharpe_ratio])
		lineageTag: 73abcc5c-c377-4f65-a5f4-a32a66baf4f2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Avg_CAGR_3Y = AVERAGEX(FILTER(fund_metrics, fund_metrics[cagr_3y] <> BLANK()), fund_metrics[cagr_3y])
		lineageTag: 2f9b270f-8f15-4a98-9351-bded5e885b28

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Fund_Count = DISTINCTCOUNT(fund_metrics[scheme_code])
		formatString: 0
		lineageTag: 276e4864-0297-4270-9924-082ca159447d

	measure Avg_Volatility = AVERAGEX(FILTER(fund_metrics, fund_metrics[volatility_pct] <> BLANK()), fund_metrics[volatility_pct])
		lineageTag: a1ee75ee-6bf8-477d-a9a9-6f312ac82246

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Avg_Max_Drawdown = AVERAGEX(FILTER(fund_metrics, fund_metrics[max_drawdown_pct] <> BLANK()), fund_metrics[max_drawdown_pct])
		lineageTag: 4c1ab044-60ec-4183-886d-5cd39938d188

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg CAGR 1Y (%)' =
			
			AVERAGEX( FILTER(fund_metrics, fund_metrics[cagr_1y] <> BLANK()), fund_metrics[cagr_1y] )
		lineageTag: c06f7420-017c-4131-a595-8af3ea495144

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg CAGR 5Y (%)' =
			
			AVERAGEX( FILTER(fund_metrics, fund_metrics[cagr_5y] <> BLANK()), fund_metrics[cagr_5y] )
		lineageTag: 50eb6154-179e-4fb2-9dc9-281c1e475abd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Max_Composite_Score = MAXX(fund_metrics, fund_metrics[composite_score])
		lineageTag: d4515df3-018e-4954-ae1a-2ea3592ed47e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Avg_Sortino_Ratio = AVERAGEX(FILTER(fund_metrics, fund_metrics[sortino_ratio] <> BLANK()), fund_metrics[sortino_ratio])
		lineageTag: 62dc9a9c-d765-4dcd-be94-51b1f6f84f3b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Category_Peer_Count = CALCULATE(DISTINCTCOUNT(fund_metrics[scheme_code]), ALLEXCEPT(fund_metrics, fund_metrics[sub_category]))
		formatString: 0
		lineageTag: 3dbc1438-6709-4717-b3c5-3724fdaeb468

	column Value
		formatString: 0
		lineageTag: 5ea69001-e7e4-493a-8dfb-3def6230a330
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition _Measures = calculated
		mode: import
		source = {1}

	annotation PBI_Id = b6bdef5fcf134a859e52a043a1cc2e45

