table benchmark_data_clean
	lineageTag: 9a274e9c-6aac-4b63-9521-c1a98da1ed34

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: c27c6e87-912a-4e54-b5a8-7d7943ffffbf
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: c625cb16-8488-422c-b913-aa42c1c9054e
			defaultHierarchy: LocalDateTable_397628ff-9418-472b-9fa9-fd310417d934.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Nifty 50'
		dataType: double
		lineageTag: d0ba8ad1-643f-40bd-a4fd-5a321ae13075
		summarizeBy: sum
		sourceColumn: Nifty 50

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Nifty 500'
		dataType: double
		lineageTag: d51258ef-15c5-45e9-a5e5-0b63777b7915
		summarizeBy: sum
		sourceColumn: Nifty 500

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Nifty Midcap 150'
		dataType: double
		lineageTag: 669d3cd2-bb4c-4e44-8315-f5b8b335498d
		summarizeBy: sum
		sourceColumn: Nifty Midcap 150

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Nifty Smallcap 250'
		dataType: double
		lineageTag: 06a29cce-d44a-4cbe-a0fb-e32f0c086413
		summarizeBy: sum
		sourceColumn: Nifty Smallcap 250

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Nifty Next 50'
		dataType: double
		lineageTag: 17cca520-4fc7-4664-8383-d4bd0ef0375b
		summarizeBy: sum
		sourceColumn: Nifty Next 50

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'BSE Sensex'
		dataType: double
		lineageTag: 5ad1fb8d-4d83-4907-99ad-995ac4951b70
		summarizeBy: sum
		sourceColumn: BSE Sensex

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Nifty Bank'
		dataType: double
		lineageTag: 697cfbd2-0cc7-413f-9821-1c152b8151df
		summarizeBy: sum
		sourceColumn: Nifty Bank

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'India 10Y Bond'
		dataType: double
		lineageTag: 5d963118-2e29-4e58-8d60-72c03aced09f
		summarizeBy: sum
		sourceColumn: India 10Y Bond

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition benchmark_data_clean = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\anude\OneDrive\Documents\codeBase\mutual_funds\data\cleaned\benchmark_data_clean.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"date", type date}, {"Nifty 50", type number}, {"Nifty 500", type number}, {"Nifty Midcap 150", type number}, {"Nifty Smallcap 250", type number}, {"Nifty Next 50", type number}, {"BSE Sensex", type number}, {"Nifty Bank", type number}, {"India 10Y Bond", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

