table category_reference_clean
	lineageTag: e9c498ff-329e-43fe-bd52-c963b1a11782

	column broad_category
		dataType: string
		lineageTag: f68e450a-e69c-487f-b49d-8dc81976691f
		summarizeBy: none
		sourceColumn: broad_category

		annotation SummarizationSetBy = Automatic

	column sub_category
		dataType: string
		lineageTag: 8ad50681-aee3-4498-aa97-29663d045b03
		summarizeBy: none
		sourceColumn: sub_category

		annotation SummarizationSetBy = Automatic

	column benchmark_index
		dataType: string
		lineageTag: c2811730-458c-4c8b-9d57-6772e3000eb3
		summarizeBy: none
		sourceColumn: benchmark_index

		annotation SummarizationSetBy = Automatic

	column risk_level
		dataType: string
		lineageTag: 2e704317-4d28-470e-bb51-fb0f42604055
		summarizeBy: none
		sourceColumn: risk_level

		annotation SummarizationSetBy = Automatic

	partition category_reference_clean = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\prith\OneDrive\Desktop\Mutual Fund Dashboard\Power Bi\category_reference_clean.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"broad_category", type text}, {"sub_category", type text}, {"benchmark_index", type text}, {"risk_level", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

