table fund_metrics
	lineageTag: 06426427-6dc0-4bfc-a596-c7fb25d0feca

	column scheme_code
		dataType: int64
		formatString: 0
		lineageTag: 16ace832-4eb2-412a-8c0a-4f3664500828
		summarizeBy: none
		sourceColumn: scheme_code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fund_name
		dataType: string
		lineageTag: a4e6627f-3833-4eae-afec-9e1b9f8aace5
		summarizeBy: none
		sourceColumn: fund_name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fund_house
		dataType: string
		lineageTag: af75e15e-65b2-40e1-9ae2-3d9982d688ad
		summarizeBy: none
		sourceColumn: fund_house

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column broad_category
		dataType: string
		lineageTag: 5646f16c-9a76-4e17-9e1e-01a2fa1eee2f
		summarizeBy: none
		sourceColumn: broad_category

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column sub_category
		dataType: string
		lineageTag: d4d9bc73-666a-45bb-be58-4860da70ac33
		summarizeBy: none
		sourceColumn: sub_category

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column full_category
		dataType: string
		lineageTag: 1fdf98bd-76cc-47c7-86d5-39b245c65471
		summarizeBy: none
		sourceColumn: full_category

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column scheme_type
		dataType: string
		lineageTag: 9b807bc3-3f80-49ba-a320-d8a74e547d8a
		summarizeBy: none
		sourceColumn: scheme_type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column benchmark_used
		dataType: string
		lineageTag: 05473ae7-1c75-45fe-a0c8-ca3f5677541b
		summarizeBy: none
		sourceColumn: benchmark_used

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column inception_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 45e20f66-ff96-4508-a4cc-0b68f15c2cf3
		summarizeBy: none
		sourceColumn: inception_date

		variation Variation
			isDefault
			relationship: ab9c22bd-8bc8-4cfc-a659-182a39853f03
			defaultHierarchy: LocalDateTable_03f6d714-7a8a-4517-92e9-b413f5b47551.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column fund_age_years
		dataType: int64
		formatString: 0
		lineageTag: df27364d-62a1-4054-aee6-a2071a83b66f
		summarizeBy: sum
		sourceColumn: fund_age_years

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column total_nav_days
		dataType: int64
		formatString: 0
		lineageTag: 717bdd53-5f88-4229-90fc-4237938202d1
		summarizeBy: sum
		sourceColumn: total_nav_days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column latest_nav
		dataType: double
		lineageTag: 7f7c8fe1-39c5-463d-b7bb-67140e3f80b7
		summarizeBy: sum
		sourceColumn: latest_nav

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column nav_52w_high
		dataType: double
		lineageTag: 6a4e4b9e-009c-4744-9ef0-82c529ee81c6
		summarizeBy: sum
		sourceColumn: nav_52w_high

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column nav_52w_low
		dataType: double
		lineageTag: e3421814-3f00-4f40-b2ad-19074425fc13
		summarizeBy: sum
		sourceColumn: nav_52w_low

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column nav_52w_change_pct
		dataType: double
		lineageTag: a7f6a529-8377-4442-b79c-ea0db84d8bb8
		summarizeBy: sum
		sourceColumn: nav_52w_change_pct

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cagr_1y
		dataType: double
		lineageTag: 8fc1796f-bcf9-483e-88eb-f21c8dda4b7a
		summarizeBy: sum
		sourceColumn: cagr_1y

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cagr_3y
		dataType: double
		lineageTag: 760f758b-e6fb-4750-8af6-f2e9b6e5f253
		summarizeBy: sum
		sourceColumn: cagr_3y

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cagr_5y
		dataType: double
		lineageTag: c17b0d98-f350-4965-9ef1-9cef66b6588d
		summarizeBy: sum
		sourceColumn: cagr_5y

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column return_1m_pct
		dataType: double
		lineageTag: 5a685308-3708-4d81-bfe2-67eb9d5592d7
		summarizeBy: sum
		sourceColumn: return_1m_pct

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column return_3m_pct
		dataType: double
		lineageTag: ecda6cdd-fc76-4700-bcd0-a6cd00491863
		summarizeBy: sum
		sourceColumn: return_3m_pct

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column return_6m_pct
		dataType: double
		lineageTag: 51b5b431-35c0-4bac-9c54-6fb16505db23
		summarizeBy: sum
		sourceColumn: return_6m_pct

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column return_1y_pct
		dataType: double
		lineageTag: 74490d7d-bf90-42ef-8988-90f08c230e3e
		summarizeBy: sum
		sourceColumn: return_1y_pct

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cagr_3y_snap
		dataType: double
		lineageTag: 1278536d-54a1-4545-ac5d-b576fd767d1a
		summarizeBy: sum
		sourceColumn: cagr_3y_snap

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cagr_5y_snap
		dataType: double
		lineageTag: f4c38c11-650e-43c2-a559-12b0c158b8eb
		summarizeBy: sum
		sourceColumn: cagr_5y_snap

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column volatility_pct
		dataType: double
		lineageTag: ce274395-914c-4321-aa9e-9871aafeec9b
		summarizeBy: sum
		sourceColumn: volatility_pct

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column max_drawdown_pct
		dataType: double
		lineageTag: 5d58c56c-4145-42a7-b976-b9384889a146
		summarizeBy: sum
		sourceColumn: max_drawdown_pct

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column beta
		dataType: double
		lineageTag: cf354cf4-ba53-492b-aabd-7b6ad71bc50e
		summarizeBy: sum
		sourceColumn: beta

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column tracking_error_pct
		dataType: double
		lineageTag: b6fe8b6f-e96f-4d92-83bc-ccd8e7401656
		summarizeBy: sum
		sourceColumn: tracking_error_pct

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sharpe_ratio
		dataType: double
		lineageTag: 22b482aa-7452-4f75-a73c-f52370adaf79
		summarizeBy: sum
		sourceColumn: sharpe_ratio

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sortino_ratio
		dataType: double
		lineageTag: 96bf9e6d-5d12-45a3-8f2d-40ecd318c01f
		summarizeBy: sum
		sourceColumn: sortino_ratio

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column calmar_ratio
		dataType: double
		lineageTag: a612448e-370f-46e8-aa62-ad3af131f145
		summarizeBy: sum
		sourceColumn: calmar_ratio

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column alpha_pct
		dataType: double
		lineageTag: a2b49fba-f2fe-44c4-a4a3-f237a9458c2c
		summarizeBy: sum
		sourceColumn: alpha_pct

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column composite_score
		dataType: double
		lineageTag: 419596d9-8bd7-4fa9-b60a-8cee46485ddd
		summarizeBy: sum
		sourceColumn: composite_score

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column universe_rank
		dataType: int64
		formatString: 0
		lineageTag: c3890fc5-5d96-45b3-b8d1-037f880f5937
		summarizeBy: sum
		sourceColumn: universe_rank

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column category_rank
		dataType: int64
		formatString: 0
		lineageTag: 4a51feb1-8364-45fd-b993-651f31c822f0
		summarizeBy: sum
		sourceColumn: category_rank

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition fund_metrics = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\prith\OneDrive\Desktop\Mutual Fund Dashboard\Power Bi\fund_metrics.csv"),[Delimiter=",", Columns=35, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"scheme_code", Int64.Type}, {"fund_name", type text}, {"fund_house", type text}, {"broad_category", type text}, {"sub_category", type text}, {"full_category", type text}, {"scheme_type", type text}, {"benchmark_used", type text}, {"inception_date", type date}, {"fund_age_years", Int64.Type}, {"total_nav_days", Int64.Type}, {"latest_nav", type number}, {"nav_52w_high", type number}, {"nav_52w_low", type number}, {"nav_52w_change_pct", type number}, {"cagr_1y", type number}, {"cagr_3y", type number}, {"cagr_5y", type number}, {"return_1m_pct", type number}, {"return_3m_pct", type number}, {"return_6m_pct", type number}, {"return_1y_pct", type number}, {"cagr_3y_snap", type number}, {"cagr_5y_snap", type number}, {"volatility_pct", type number}, {"max_drawdown_pct", type number}, {"beta", type number}, {"tracking_error_pct", type number}, {"sharpe_ratio", type number}, {"sortino_ratio", type number}, {"calmar_ratio", type number}, {"alpha_pct", type number}, {"composite_score", type number}, {"universe_rank", Int64.Type}, {"category_rank", Int64.Type}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","Index Fund - Nifty 50","",Replacer.ReplaceText,{"sub_category"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Index Funds ","Index Fund - Nifty 50",Replacer.ReplaceText,{"sub_category"})
				in
				    #"Replaced Value1"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

